(source gnu)
(source melpa)

(package "eclim" "@VERSION" "Eclim provides the ability to access Eclipse code editing features")

(depends-on "dash")
(depends-on "json")
(depends-on "popup")
(depends-on "s")
(depends-on "cl-lib")
(depends-on "yasnippet")
(development
 (depends-on "company")
 (depends-on "auto-complete")
 (depends-on "elisp-lint")
 (depends-on "buttercup")
 (depends-on "ert")
 (depends-on "ert-runner")
 (depends-on "noflet")
 (depends-on "cask-package-toolset")
 (depends-on "undercover"))
